/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LeaveApplication } from "./LeaveApplication";
import { LeaveApplicationCountArgs } from "./LeaveApplicationCountArgs";
import { LeaveApplicationFindManyArgs } from "./LeaveApplicationFindManyArgs";
import { LeaveApplicationFindUniqueArgs } from "./LeaveApplicationFindUniqueArgs";
import { CreateLeaveApplicationArgs } from "./CreateLeaveApplicationArgs";
import { UpdateLeaveApplicationArgs } from "./UpdateLeaveApplicationArgs";
import { DeleteLeaveApplicationArgs } from "./DeleteLeaveApplicationArgs";
import { Employee } from "../../employee/base/Employee";
import { LeaveType } from "../../leaveType/base/LeaveType";
import { LeaveApplicationWhereInput } from "./LeaveApplicationWhereInput";
import { LeaveApplicationService } from "../leaveApplication.service";
@graphql.Resolver(() => LeaveApplication)
export class LeaveApplicationResolverBase {
  constructor(protected readonly service: LeaveApplicationService) {}

  async _leaveApplicationsMeta(
    @graphql.Args() args: LeaveApplicationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LeaveApplication])
  async leaveApplications(
    @graphql.Args() args: LeaveApplicationFindManyArgs
  ): Promise<LeaveApplication[]> {
    return this.service.leaveApplications(args);
  }

  @graphql.Query(() => LeaveApplication, { nullable: true })
  async leaveApplication(
    @graphql.Args() args: LeaveApplicationFindUniqueArgs
  ): Promise<LeaveApplication | null> {
    const result = await this.service.leaveApplication(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LeaveApplication)
  async createLeaveApplication(
    @graphql.Args() args: CreateLeaveApplicationArgs
  ): Promise<LeaveApplication> {
    return await this.service.createLeaveApplication({
      ...args,
      data: {
        ...args.data,

        employee: args.data.employee
          ? {
              connect: args.data.employee,
            }
          : undefined,

        leaveType: args.data.leaveType
          ? {
              connect: args.data.leaveType,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => LeaveApplication)
  async updateLeaveApplication(
    @graphql.Args() args: UpdateLeaveApplicationArgs
  ): Promise<LeaveApplication | null> {
    try {
      return await this.service.updateLeaveApplication({
        ...args,
        data: {
          ...args.data,

          employee: args.data.employee
            ? {
                connect: args.data.employee,
              }
            : undefined,

          leaveType: args.data.leaveType
            ? {
                connect: args.data.leaveType,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LeaveApplication)
  async deleteLeaveApplication(
    @graphql.Args() args: DeleteLeaveApplicationArgs
  ): Promise<LeaveApplication | null> {
    try {
      return await this.service.deleteLeaveApplication(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Employee, {
    nullable: true,
    name: "employee",
  })
  async getEmployee(
    @graphql.Parent() parent: LeaveApplication
  ): Promise<Employee | null> {
    const result = await this.service.getEmployee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => LeaveType, {
    nullable: true,
    name: "leaveType",
  })
  async getLeaveType(
    @graphql.Parent() parent: LeaveApplication
  ): Promise<LeaveType | null> {
    const result = await this.service.getLeaveType(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Query(() => [LeaveApplication])
  async FetchMyAttendance(
    @graphql.Args()
    args: LeaveApplicationWhereInput
  ): Promise<LeaveApplication[]> {
    return this.service.FetchMyAttendance(args);
  }
}
