/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EmployeeWhereUniqueInput } from "../../employee/base/EmployeeWhereUniqueInput";

import {
  ValidateNested,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { LeaveTypeWhereUniqueInput } from "../../leaveType/base/LeaveTypeWhereUniqueInput";
import { EnumLeaveApplicationStatus } from "./EnumLeaveApplicationStatus";

@InputType()
class LeaveApplicationUpdateInput {
  @ApiProperty({
    required: false,
    type: () => EmployeeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EmployeeWhereUniqueInput)
  @IsOptional()
  @Field(() => EmployeeWhereUniqueInput, {
    nullable: true,
  })
  employee?: EmployeeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  employeeId?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  justification?: string | null;

  @ApiProperty({
    required: false,
    type: () => LeaveTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LeaveTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => LeaveTypeWhereUniqueInput, {
    nullable: true,
  })
  leaveType?: LeaveTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  managerComment?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumLeaveApplicationStatus,
  })
  @IsEnum(EnumLeaveApplicationStatus)
  @IsOptional()
  @Field(() => EnumLeaveApplicationStatus, {
    nullable: true,
  })
  status?: "Option1" | null;
}

export { LeaveApplicationUpdateInput as LeaveApplicationUpdateInput };
