/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Audit } from "./Audit";
import { AuditCountArgs } from "./AuditCountArgs";
import { AuditFindManyArgs } from "./AuditFindManyArgs";
import { AuditFindUniqueArgs } from "./AuditFindUniqueArgs";
import { CreateAuditArgs } from "./CreateAuditArgs";
import { UpdateAuditArgs } from "./UpdateAuditArgs";
import { DeleteAuditArgs } from "./DeleteAuditArgs";
import { AuditService } from "../audit.service";
@graphql.Resolver(() => Audit)
export class AuditResolverBase {
  constructor(protected readonly service: AuditService) {}

  async _auditsMeta(
    @graphql.Args() args: AuditCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Audit])
  async audits(@graphql.Args() args: AuditFindManyArgs): Promise<Audit[]> {
    return this.service.audits(args);
  }

  @graphql.Query(() => Audit, { nullable: true })
  async audit(
    @graphql.Args() args: AuditFindUniqueArgs
  ): Promise<Audit | null> {
    const result = await this.service.audit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Audit)
  async createAudit(@graphql.Args() args: CreateAuditArgs): Promise<Audit> {
    return await this.service.createAudit({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Audit)
  async updateAudit(
    @graphql.Args() args: UpdateAuditArgs
  ): Promise<Audit | null> {
    try {
      return await this.service.updateAudit({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Audit)
  async deleteAudit(
    @graphql.Args() args: DeleteAuditArgs
  ): Promise<Audit | null> {
    try {
      return await this.service.deleteAudit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
